Database screenshots added
VostrikovaVera/Module4_Task1 pull request #1
Opened 2021-04-13 08:31 UTC by VostrikovaVera

2021-04-13 18:14 UTC, MarinaRybalko commented
Хорошая работа.
Единственное у меня есть замечания к таблице Client. Что описывают поля ContactFirstName и ContactLastName? Если это контакты клиента, то есть доверенные люди клиента к которым можно обращаться по каким либо вопросам, то тут принципиально неправильно построена связь. Контакт клиента это отдельная сущность. Почему? Single Responsibility. Таблица Клиент менятся должно только когда информация о нем меняется, а не о его контактах. Подумай о перенесении контактов в отдельную таблицу и установлению связи. Либо замени эти поля в таблице Клиент на другие.
И тоже не пойму в таблице Клиент что значит StartDateOfWork и EndDateOfWork? Обычно, если хочешь понимать текущий это клиент или старый, то добавляют bit поле IsActive/IsCurrent. В будущем с этим проще работать.  Подумай над этим тоже. 

![image](https://user-images.githubusercontent.com/35547726/114599607-fd643980-9c9b-11eb-9f5e-57a8b0e2c045.png)

2021-04-13 18:14 UTC, MarinaRybalko requested changes
Надо исправить))

2021-04-14 09:45 UTC, VostrikovaVera commented
> Надо исправить))

Вынесла контакты клиента в отдельную таблицу и связала таблицу ClientContact с таблицей Client

2021-04-16 22:17 UTC, MarinaRybalko commented
Perfect!

2021-04-16 22:17 UTC, merged